---
- name: Download
  git: repo=https://github.com/Homebrew/install.git dest={{ homebrew_installer_root }}/homebrew-installer

- name: Install
  command: creates=/usr/local/bin/brew {{ homebrew_installer_root }}/homebrew-installer/install

- name: Update
  homebrew: update_homebrew=yes
  when: homebrew_update

- name: Upgrade
  homebrew: upgrade_all=yes
  when: homebrew_upgrade_all

- name: Install libraries
  homebrew: name={{ item }} state=present
  with_items: homebrew_libraries
