---
- name: Setup
  sudo: yes
  file: dest={{ homebrew_root }} owner={{ ansible_ssh_user }} state=directory

- name: Determine Homebrew version
  set_fact:
    homebrew_repo_name: "{{ 'homebrew' if ansible_os_family == 'Darwin' else 'linuxbrew' }}"

- name: Install
  shell: creates={{ homebrew_root }}/bin/brew curl -fsSL https://github.com/Homebrew/{{ homebrew_repo_name }}/tarball/master | tar xz --strip 1 -C {{ homebrew_root }}

- name: Update
  homebrew: update_homebrew=yes
  when: homebrew_update

- name: Upgrade
  homebrew: upgrade_all=yes
  when: homebrew_upgrade_all

- name: Install libraries
  homebrew: name={{ item }} state=present
  with_items: homebrew_libraries

- include: casks.yml
  when: homebrew_casks or homebrew_casks_with_sudo
