---
- name: Setup
  become: no
  file: dest={{ homebrew_root }} owner={{ ansible_ssh_user }} state=directory

- name: Determine Homebrew version
  set_fact:
    homebrew_repo_name: "{{ 'homebrew' if ansible_os_family == 'Darwin' else 'linuxbrew' }}"

- stat: path="~/{{ homebrew_repo_name }}"
  register: linuxbrew_installed

- name: Fetch
  get_url:
      url: https://raw.githubusercontent.com/Linuxbrew/install/master/install
      dest: ~/tmp/install
      mode: 0700
  when: linuxbrew_installed.stat.exists != True

- name: Install
  command: test -x ~/tmp/install
  when: linuxbrew_installed.stat.exists != True

- name: Update
  homebrew: update_homebrew=yes
  when: homebrew_update

- name: Upgrade
  homebrew: upgrade_all=yes
  when: homebrew_upgrade_all

- name: Install libraries
  homebrew: name={{ item }} state=present
  with_items: "{{ homebrew_libraries }}"

- include: casks.yml
  when: homebrew_casks or homebrew_casks_with_sudo
