---
- name: Setup
  file: dest={{ homebrew_root }} state=directory

- name: Install
  shell: creates={{ homebrew_root }}/bin/brew curl -L https://github.com/Homebrew/homebrew/tarball/master | tar xz --strip 1 -C {{ homebrew_root }}

- name: Update
  homebrew: update_homebrew=yes
  when: homebrew_update

- name: Upgrade
  homebrew: upgrade_all=yes
  when: homebrew_upgrade_all

- name: Install libraries
  homebrew: name={{ item }} state=present
  with_items: homebrew_libraries
